CREATE TABLE BOOKS (ID INTEGER NOT NULL, AUTHOR VARCHAR(255) NOT NULL, PAGES INTEGER, PRICE DECIMAL(10,2), PUBLISHEDAT DATE, STOCKSTATUS VARCHAR(255), TITLE VARCHAR(255) NOT NULL, PRIMARY KEY (ID))
CREATE TABLE SEQUENCE (SEQ_NAME VARCHAR(50) NOT NULL, SEQ_COUNT DECIMAL(15), PRIMARY KEY (SEQ_NAME))
INSERT INTO SEQUENCE(SEQ_NAME, SEQ_COUNT) values ('SEQ_GEN', 0)
